require 'oj'
require 'multi_json'
require 'typhoeus'
require 'faraday'
require 'typhoeus/adapters/faraday'

require_relative 'ontologies_api_client/config'
require_relative 'ontologies_api_client/http'
require_relative 'ontologies_api_client/link_explorer'
require_relative 'ontologies_api_client/base'
require_relative 'ontologies_api_client/collection'
require_relative 'ontologies_api_client/read_write'
